<a href="https://colab.research.google.com/github/venkateswaran-online/Scaler-Lecture-Notes/blob/main/AR_DAV1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l = [20,40,45]#sal in thousand

In [ ]:
l +10

TypeError: can only concatenate list (not "int") to list

In [ ]:
import numpy as np

In [ ]:
ar1 = np.array(l)

In [ ]:
ar1

array([20, 40, 45])

In [ ]:
ar1+10

array([30, 50, 55])

In [ ]:
import time
import numpy as np

# Large list and array to compare performance
large_list = list(range(1_000_000))
large_array = np.arange(1_000_000)

# Timing sum on a Python list
start = time.time()
sum_list = sum(large_list)
end = time.time()
list_time = end - start

# Timing sum on a NumPy array
start = time.time()
sum_array = np.sum(large_array)
end = time.time()
array_time = end - start

print("List sum time:", list_time, "seconds")
print("Array sum time:", array_time, "seconds")

List sum time: 0.00939035415649414 seconds
Array sum time: 0.0019037723541259766 seconds


In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


In [ ]:
#strings - "800"

In [ ]:
votes_times_two = votes * 2
votes_times_two

array([1550, 1574, 1836,  176,  332,  572, 5112,  648, 1008,  804])

In [ ]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
a1.ndim

1

In [ ]:
a1.shape # 1d  it is the count of elements

(3,)

In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,1,12]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1, 12]])

In [ ]:
a2.ndim

2

In [ ]:
a2.shape

(4, 3)

In [ ]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,1,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10,  1, 12]]])

In [ ]:
a3.ndim

3

In [ ]:
a3.shape

(2, 2, 3)

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
votes.ndim

1

In [ ]:
votes.shape

(10,)

In [ ]:
(10,)

(10,)

In [ ]:
#np.array(l)

In [ ]:
two_d_data = np.array([
    votes,costs
])

In [ ]:
two_d_data

array([['775', '787', '918', '88', '166', '286', '2556', '324', '504',
        '402'],
       ["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
        "'600.0'", "'700.0'", "'550.0'", "'500.0'"]], dtype='<U21')

In [ ]:
two_d_data.shape

(2, 10)

In [ ]:
two_d_data.T

array([['775', "'800.0'"],
       ['787', "'800.0'"],
       ['918', "'800.0'"],
       ['88', "'300.0'"],
       ['166', "'600.0'"],
       ['286', "'600.0'"],
       ['2556', "'600.0'"],
       ['324', "'700.0'"],
       ['504', "'550.0'"],
       ['402', "'500.0'"]], dtype='<U21')

In [ ]:
#string>float>int>bool

In [ ]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
np.char.replace(np.array(["utkarsh"]),"ut","HT")

array(['HTkarsh'], dtype='<U7')

In [ ]:
#np.char.replace(costs, what needs to be replaced, what value you want to put)
c = np.char.replace(costs, "'", '')
c

array(['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
       '700.0', '550.0', '500.0'], dtype='<U5')

In [ ]:
c1 = c.astype(float)
c1

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
c1.astype(int)

array([800, 800, 800, 300, 600, 600, 600, 700, 550, 500])

In [ ]:
costs.dtype

dtype('<U7')

In [ ]:
mixed_data = np.array([100, '200', 300, 'gaurav'])
mixed_data

array(['100', '200', '300', 'gaurav'], dtype='<U21')

In [ ]:
mixed_int = mixed_data.astype(int)

ValueError: invalid literal for int() with base 10: np.str_('gaurav')

In [ ]:
c1

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
c1[7]

np.float64(700.0)

In [ ]:
c1[-3]

np.float64(700.0)

In [ ]:
c1

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
      0       1     2     3     4     5     6     7     8     9
array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
#c1[start:end+1]
c1[3:8+1]

array([300., 600., 600., 600., 700., 550.])

In [ ]:
c1[-7:-2+1]

array([300., 600., 600., 600., 700., 550.])

In [ ]:
c1[3:3453445634]

array([300., 600., 600., 600., 700., 550., 500.])