<a href="https://colab.research.google.com/github/venkateswaran-online/Scaler-Lecture-Notes/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Open this Sheet to take a look at the Data [link](https://docs.google.com/spreadsheets/d/1zcVsqjSWrY67_X7kbOIMIenuNVkoLyEeEz7NNly-WrY)



In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])
rate = np.array([4.1, 3.8, 4.0, 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

print("Votes (Array):", votes)
print("Costs (Array):", costs)
print("Ratings (Array):", rate)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]
Ratings (Array): [4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]


In [ ]:
import numpy as np

# Your numeric_data array
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

# Just to display in a good way
# Set print options to suppress scientific notation
np.set_printoptions(suppress=True, precision=1)

# Print the array
print("Numeric data (formatted):")
print(numeric_data)

Numeric data (formatted):
[[   4.1  775.   800. ]
 [   3.8  787.   800. ]
 [   4.   918.   800. ]
 [   2.6   88.   300. ]
 [   1.1  166.   600. ]
 [   3.5  286.   600. ]
 [   4.7 2556.   600. ]
 [   2.5  324.   700. ]
 [   2.8  504.   550. ]
 [   3.4  402.   500. ]]




---


## **1. Sorting in NumPy**

### 1. Sorting a 1D Array 🗂️

We’ll sort a simple 1D array using:
- <font color="magenta">np.sort()</font>: Returns a sorted copy.
- <font color="magenta">np.argsort()</font>: Returns indices that would sort the array.


In [ ]:
sorted_votes = np.sort(votes)       # Sort the votes
print("Sorted Votes:", sorted_votes[:10])  # Display the first 10 sorted values

Sorted Votes: [  88  166  286  324  402  504  775  787  918 2556]


In [ ]:
sorted_indices = np.argsort(votes)  # Indices that would sort the votes
print("Indices for Sorting:", sorted_indices[:10])

Indices for Sorting: [3 4 5 7 9 8 0 1 2 6]


Explanation:

- ```np.sort(votes)``` creates a sorted copy of the votes array without altering the original.
- ```np.argsort(votes)``` provides the indices required to sort the array. Useful for sorting related columns.

### 2. Sorting a 2D Array 📊

Sorting can be done along rows or columns:
- Use the <font color="Pink">axis</font> parameter:
  - `axis=0`: Sort each column.
  - `axis=1`: Sort each row.


In [ ]:
# Example 2D array
array_2d = np.array([[34, 11, 8],
                     [7, 45, 18],
                     [9, 23, 20]])

# Sort along rows (axis=1)
sorted_rows = np.sort(array_2d, axis=1)

# Sort along columns (axis=0)
sorted_columns = np.sort(array_2d, axis=0)

print("Original 2D Array: \n", array_2d)
print("---"* 10)
print("Sorted along Rows: \n", sorted_rows)
print("---"* 10)
print("Sorted along Columns: \n", sorted_columns)

Original 2D Array: 
 [[34 11  8]
 [ 7 45 18]
 [ 9 23 20]]
------------------------------
Sorted along Rows: 
 [[ 8 11 34]
 [ 7 18 45]
 [ 9 20 23]]
------------------------------
Sorted along Columns: 
 [[ 7 11  8]
 [ 9 23 18]
 [34 45 20]]


**Explanation:**

- `axis=1` sorts each row independently.
- `axis=0` sorts each column independently.







In [ ]:
# Sorting by ratings
ratings = numeric_data[:, 0]  # Extract 'rate' column
sorted_indices_by_rating = np.argsort(ratings)
sorted_ratings = ratings[sorted_indices_by_rating]

print("Sorted Ratings:\n", sorted_ratings[:10])  # Show top 10 sorted ratings

Sorted Ratings:
 [1.1 2.5 2.6 2.8 3.4 3.5 3.8 4.  4.1 4.7]


**Explanation:**
- <font color="magenta">np.argsort()</font> provides indices to sort the ratings.
- We can use these indices to sort the corresponding rows or another column (e.g., costs or votes).



---




## **2. Matrix Multiplication in NumPy**



### 1. Element-wise Multiplication 🧮

Element-wise multiplication multiplies corresponding elements in two arrays.
This uses the <font color="red">*</font> operator in NumPy.

We’ll perform element-wise multiplication on numeric columns like:
- `votes` and `rate`: To calculate a **weighted vote score**.

In [ ]:
# This is array multiply by array of same shape

# Element-wise multiplication
votes = numeric_data[:, 1]  # Extract 'votes'
weighted_scores = votes * ratings

print("Weighted scores (sample):\n", weighted_scores[:5])

Weighted scores (sample):
 [3177.5 2990.6 3672.   228.8  182.6]


**Explanation:**

- Element-wise multiplication combines ratings and votes to create a weighted metric.
- This can be used for scoring restaurants based on popularity and quality.


In [ ]:
# This is array multiply by number

votes = numeric_data[:, 1]  # Extract 'votes'
vote_by_5 = votes * 5

print(vote_by_5[:5])

[3875. 3935. 4590.  440.  830.]


In [ ]:
# This is array multiply by array of different shape

votes = numeric_data[:, 1]  # Extract 'votes'
vote_by_array = votes * np.array([1,2,3,4])

print(vote_by_array)

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

**Takeaway:**

- Array * Number $\rightarrow$ WORKS
- Array * Array (same shape) $\rightarrow$ WORKS
- Array * Array (different shape) $\rightarrow$ DOES NOT WORK

### 2. Matrix Multiplication 📐

We’ll calculate a transformation using:
- **Ratings**, **Votes**, and **Approximate Costs**.
- Methods:
  - <font color="magenta">np.dot()</font>
  - <font color="magenta">np.matmul()</font>
  - <font color="magenta">@</font> operator.


In [ ]:
# Create a random transformation matrix
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])

# Matrix multiplication using np.dot()
transformed_data_dot = np.dot(numeric_data, transformation_matrix)

# Matrix multiplication using @ operator
transformed_data_at = numeric_data @ transformation_matrix

# Matrix multiplication using np.matmul()
transformed_data_matmul = np.matmul(numeric_data, transformation_matrix)

print("Transformed Data (np.dot):\n", transformed_data_dot[:5])
print("---"* 10)
print("Transformed Data (@ operator):\n", transformed_data_at[:5])
print("---"* 10)
print("Transformed Data (np.matmul):\n", transformed_data_matmul[:5])
print("---"* 10)

Transformed Data (np.dot):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------
Transformed Data (@ operator):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------
Transformed Data (np.matmul):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------


**Explanation:**

- A transformation matrix allows us to apply scaling and weighting to the original data.
- <font color="magenta">np.dot()</font>, <font color="magenta">@</font>, and <font color="magenta">np.matmul()</font> produce the same results for matrix multiplication.



**Rule:** Number of columns of the first matrix should be equal to number of rows of the second matrix.

- (A,B) * (B,C) -> (A,C)
- (3,4) * (4,3) -> (3,3)

Visual Demo: https://www.geogebra.org/m/ETHXK756





In [ ]:
a = np.array([1,2,3,4])

a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.dot(a, 5)

array([ 5, 10, 15, 20])

**Important:**

- `dot()` function supports the vector multiplication with a scalar value, which is not possible with `matmul()`.
- `Vector * Vector` will work for `matmul()` but `Vector * Scalar` won't.



---



## **3. Vectorization in NumPy 🚀**


### Why Vectorization is Necessary

## 1. The Problem with Non-Vectorized Operations ⚠️

When working with arrays, applying a Python function directly to a NumPy array often leads to errors.  

Let’s see an example where we try to use a Python function on a column of the dataset.

In [ ]:
# Example: Apply a custom function to the 'rate' column
def categorize_rating(rating):
    """Categorize ratings into high or low."""
    if rating >= 4.0:
        return "High"
    else:
        return "Low"

In [ ]:
# Attempt to apply the function directly
categorized_ratings = categorize_rating(numeric_data[:, 0])  # 'rate' column
categorized_ratings

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Explanation:
- Python functions like <font color="magenta">categorize_rating</font> are not designed to work directly on NumPy arrays.
- NumPy operates on arrays element-wise, but Python functions expect single values.
- This results in a <font color="red">ValueError</font> or other unexpected behavior.


### Introducing <font color="magenta">np.vectorize()</font> 🌟

<font color="magenta">np.vectorize()</font> allows us to apply Python functions element-wise to a NumPy array.

Let’s vectorize the <font color="Greed">categorize_rating()</font> function and apply it to the `rate` column.


In [ ]:
# Vectorize the categorize_rating function
vectorized_categorize_rating = np.vectorize(categorize_rating)
vectorized_categorize_rating

In [ ]:
# Apply the vectorized function to the 'rate' column
categorized_ratings = vectorized_categorize_rating(numeric_data[:, 0])

# Display a sample of the categorized ratings
print("Categorized Ratings (sample):", categorized_ratings[:10])

Categorized Ratings (sample): ['High' 'Low' 'High' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low']


**Explanation:**
- <font color="greed">np.vectorize()</font> transforms a Python function into one that works seamlessly with arrays.
- This enables element-wise operations without needing loops.

### 3. Applying Discounts to Costs 💰

Imagine we want to apply a **10% discount** to restaurants with a rating of **4.0 or higher**.  
We’ll use <font color="greed">np.vectorize()</font> to vectorize the logic and apply it to the dataset.


In [ ]:
# Define a function to calculate discounted cost
def discount_cost(rate, cost):
    """Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

# Vectorize the discount_cost function
vectorized_discount_cost = np.vectorize(discount_cost)

# Apply the vectorized function to 'rate' and 'approx_cost(for two people)'
discounted_costs = vectorized_discount_cost(numeric_data[:, 0], numeric_data[:, 2])

# Display a sample of the discounted costs
print("Discounted Costs (sample):", discounted_costs[:10])

Discounted Costs (sample): [720. 800. 720. 300. 600. 600. 540. 700. 550. 500.]


### Explanation:
- The function <font color="blue">discount_cost()</font> checks each restaurant's rating and applies a discount if it meets the criteria.
- <font color="magenta">np.vectorize()</font> enables this logic to process the entire dataset column efficiently.



---



## **4. Broadcasting in NumPy 🚀**


### 1. What is Broadcasting?

Broadcasting allows NumPy to perform operations on arrays with **different shapes** by automatically "expanding" smaller arrays.

It simplifies computation by avoiding the need for explicit loops or manual reshaping.

💡 **Example**: Adding a scalar to a 2D array works because NumPy "broadcasts" the scalar to match the array's shape.


In [ ]:
# Example of broadcasting a scalar
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

result = array_2d + scalar
print("Array:\n", array_2d)
print("---"* 10)

print("adding Scalar:", scalar)
print("---"* 10)

print("Result after broadcasting:\n", result)

Array:
 [[1 2 3]
 [4 5 6]]
------------------------------
adding Scalar: 10
------------------------------
Result after broadcasting:
 [[11 12 13]
 [14 15 16]]


**Explanation:**
- The scalar `10` is broadcasted to match the shape of `array_2d`.
- NumPy performs the operation as if the scalar is a 2D array with the same shape.


### 2. Broadcasting in 1D Arrays

**Case 1: Dimensions of Both Arrays Are Equal ✅**

If two arrays have the same shape, operations work without any issues.


In [ ]:
# Arrays with the same shape
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
result = array1 + array2
print(f"{array1} + {array2} = {result}")

[1 2 3] + [4 5 6] = [5 7 9]


**Case 2: One Array is 1D 📏**

If one array is 1D and the other is higher-dimensional, broadcasting will expand the 1D array.


In [ ]:
# Broadcasting a 1D array to a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Broadcasting works
result = array_2d + array_1d

print(f"{array_2d} + {array_1d} =")
print("---"* 10)
print(result)

[[1 2 3]
 [4 5 6]] + [10 20 30] =
------------------------------
[[11 22 33]
 [14 25 36]]


**Explanation:**

- The 1D array `[10, 20, 30]` is broadcasted to match the rows of the 2D array.


**Case 3: Column and Row Matrices 🧩**

Broadcasting works between a column matrix and a row matrix.



In [ ]:
# Column matrix (3x1) and row matrix (1x3)
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

# Broadcasting works
result = col_matrix + row_matrix

print(f"{col_matrix} + {row_matrix} =")
print("---"* 10)
print(result)

[[1]
 [2]
 [3]] + [[10 20 30]] =
------------------------------
[[11 21 31]
 [12 22 32]
 [13 23 33]]


**Explanation:**
- The column matrix is broadcasted along the columns, and the row matrix is broadcasted along the rows.


### **Error: Some Incompatible Shapes 🚨**

Broadcasting fails when the shapes are incompatible. Let’s see an example.


In [ ]:
# Incompatible shapes
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

result = array1 + array2
result

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

**Explanation:**

- The shapes `(3,)` and `(2, 2)` are incompatible for broadcasting.


### 3. Broadcasting in 2D Arrays

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)

**Four Rules for Broadcasting in 2D Arrays 🔍**

1. If the arrays do not have the same number of dimensions, prepend 1s to the smaller array.
2. Arrays are compatible if:
   - Dimensions are the same, or
   - One of the dimensions is 1.
3. The result shape is the maximum shape along each dimension.
4. If rules are not satisfied, broadcasting fails.

Let’s explore examples of what works and what doesn’t.

In [ ]:
# Example: Compatible shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

# Broadcasting works
result = array1 + array2

print("Array 1:\n", array1)
print("---"* 10)

print("Array 2:\n", array2)
print("---"* 10)

print("Result:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]
------------------------------
Array 2:
 [[10]
 [20]]
------------------------------
Result:
 [[11 12 13]
 [24 25 26]]


**Explanation:**

- Shape of `array1` is `(2, 3)` and `array2` is `(2, 1)`.
- Broadcasting expands `array2` to `(2, 3)`.


In [ ]:
# Example: Incompatible shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])

result = array1 + array2
result

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

**Explanation:**

- Shape of `array1` is `(2, 3)` and `array2` is `(1, 2)`.
- Broadcasting fails because the dimensions are not compatible.


### 4. Using <font color="magenta">np.tile()</font>

When broadcasting doesn’t work, you can explicitly expand an array using <font color="magenta">np.tile()</font>.


In [ ]:
# Example: Explicit broadcasting with np.tile
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

# Use np.tile to match shapes
array1_tiled = np.tile(array1, (3, 1))
array1_tiled

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Perform addition
result = array1_tiled + array2
print("Result:\n", result)

Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


**Explanation:**
- <font color="magenta">np.tile()</font> repeats `array1` to match the shape of `array2`.
- Broadcasting is now possible.



---




## **5. Splitting Arrays in NumPy ✂️**

### Parameters for Splitting Arrays 🛠️

All splitting functions take the following parameters:

1. <font color="green">array</font>: The array to be split.
2. <font color="skyblue">indices_or_sections</font>:
   - If an integer `N`, the array is split into `N` equal sections.
   - If a list of indices, the splits happen at those positions.




### Splitting Arrays with <font color="green">np.split()</font>

<font color="green">np.split()</font> splits an array into sections along a specified axis:
- **axis=0**: Split rows.
- **axis=1**: Split columns (for 2D arrays).


**Example 1: Splitting a 1D Array**

In [ ]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 sections
split_1d = np.split(array_1d, 3)

print("Original Array:", array_1d)
print("Splits:", split_1d)

Original Array: [1 2 3 4 5 6]
Splits: [array([1, 2]), array([3, 4]), array([5, 6])]


**Prerequisites for Splitting 📏**

- The total number of elements **must be divisible** by the number of splits.
- For 2D arrays, ensure the axis matches the shape of the array.

💡 **Example**:
- A 1D array with 6 elements can be split into 2 or 3 equal parts, but **not 4**.
- A 2D array with 4 columns can be split horizontally into 2 parts but **not 3**.

In [ ]:
split_1d = np.split(array_1d, 4)

ValueError: array split does not result in an equal division

**Example 2: Splitting a 2D Array**

In [ ]:
# 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

# Split into 2 along axis=1 (columns)
split_2d = np.split(array_2d, 2, axis=1)

print("Original Array:\n", array_2d)
print("=="*10)
print("Splits:")
for part in split_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Explanation:**
- **1D Array**: Split into 3 equal parts.
- **2D Array**: Split columns into 2 equal sections using <font color="skyblue">axis=1</font>.

### Horizontal Splitting with <font color="skyblue">np.hsplit()</font>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/054/735/original/hvsp1.png?1698041133" width="600" height="400">


<font color="skyblue">np.hsplit()</font> splits a 2D array horizontally into sections (columns).  

💡 **Shortcut**: Equivalent to <font color="green">np.split(array, N, axis=1)</font>.

**Example: Horizontal Splitting**

In [ ]:
# Horizontal split
hsplit_2d = np.hsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("=="*10)
print("Horizontal Splits:")
for part in hsplit_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Horizontal Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Explanation:**
- <font color="blue">np.hsplit()</font>  divides the columns into equal sections.
- This is a convenient method for column-wise splitting.


### Vertical Splitting with <font color="greed">np.vsplit()</font>

<font color="gredd">np.vsplit()</font>`splits a 2D array vertically into sections (rows).  

💡 **Shortcut**: Equivalent to <font color="green">np.split(array, N, axis=0)</font>.

**Example: Vertical Splitting**

In [ ]:
# Vertical split
vsplit_2d = np.vsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("Vertical Splits:")
for part in vsplit_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Vertical Splits:
[[1 2 3 4]]
[[5 6 7 8]]


**Explanation:**

- <font color="skyblue">np.vsplit()</font> divides rows into equal sections.
- This is a convenient method for row-wise splitting.

### Custom Splits with Indices 🛠️

Instead of dividing into equal parts, we can use indices for custom splits.


In [ ]:
# Split using indices
custom_split = np.split(array_1d, [2, 5])

print("Original Array:", array_1d)
print("Custom Splits:", custom_split)

Original Array: [1 2 3 4 5 6]
Custom Splits: [array([1, 2]), array([3, 4, 5]), array([6])]


**Explanation:**

- Splits occur at positions `[2, 5]`, creating 3 parts:
  - `[1, 2]`
  - `[3, 4, 5]`
  - `[6]`.



---



## **6. Stacking Arrays in NumPy 🚀**


### Vertical Stacking with <font color="green">np.vstack()</font>

<font color="green">np.vstack()</font> stacks arrays along the vertical axis (rows).  
- All arrays **must have the same number of columns** for vertical stacking.

**Example: Vertical Stacking**

In [ ]:
import numpy as np

# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack vertically
vstack_result = np.vstack([array1, array2])

print("Array 1:", array1)
print("Array 2:", array2)
print("Vertical Stack:\n", vstack_result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


**Explanation:**

- The arrays `[1, 2, 3]` and `[4, 5, 6]` are stacked row-wise to form a 2D array.

<font color="green">np.vstack()</font> requires arrays to have the same number of columns.  

Let’s see what happens when this condition is not met.

In [ ]:
# Arrays with unequal sizes
array3 = np.array([7, 8])


vstack_error = np.vstack([array1, array3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**

- Vertical stacking fails because `array3` has fewer elements than `array1`.
- All arrays must have the same number of columns for <font color="green">np.vstack()</font>.

### Horizontal Stacking with <font color="blue">np.hstack()</font>

<font color="blue">np.hstack()</font> stacks arrays along the horizontal axis (columns).  
- All arrays **must have the same number of rows** for horizontal stacking.

**Example: Horizontal Stacking**

In [ ]:
# Define arrays
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

# Stack horizontally
hstack_result = np.hstack([array4, array5])

print("Array 4:\n", array4)
print("Array 5:\n", array5)
print("Horizontal Stack:\n", hstack_result)

Array 4:
 [[1]
 [2]
 [3]]
Array 5:
 [[4]
 [5]
 [6]]
Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]


**Explanation:**
- Arrays `array4` and `array5` are stacked column-wise to form a 2D array.

<font color="skyblue">np.hstack()</font> requires arrays to have the same number of rows.  

Let’s see what happens when this condition is not met.

In [ ]:
# Arrays with unequal rows
array6 = np.array([[7], [8]])

hstack_error = np.hstack([array4, array6])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**

- Horizontal stacking fails because `array6` has fewer rows than `array4`.
- All arrays must have the same number of rows for `<font color="blue">np.hstack()</font>`.


### General Concatenation with <font color="skyblue">np.concatenate()</font>

<font color="skyblue">np.concatenate()</font> concatenates arrays along any axis (default is `axis=0`).  
It provides more flexibility than stacking functions.

**Parameters:**
1. <font color="green">array</font>: List or tuple of arrays to concatenate.
2. <font color="skyblue">axis</font>: Axis along which to concatenate.
   - `axis=0`: Concatenate rows.
   - `axis=1`: Concatenate columns (for 2D arrays).


In [ ]:
# Example 1: Concatenation Along Rows
# Concatenate along axis=0 (rows)
concat_rows = np.concatenate([array4, array5], axis=0)

print("Concatenation Along Rows:\n", concat_rows)

Concatenation Along Rows:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**Explanation:**

- Arrays `array4` and `array5` are concatenated row-wise into a single array.

In [ ]:
# Example 2: Concatenation Along Columns
# Concatenate along axis=1 (columns)
concat_columns = np.concatenate([array4, array5], axis=1)

print("Concatenation Along Columns:\n", concat_columns)

Concatenation Along Columns:
 [[1 4]
 [2 5]
 [3 6]]


**Explanation:**
- Arrays `array4` and `array5` are concatenated column-wise into a single array.

<font color="skyblue">np.concatenate()</font> requires compatible dimensions along the non-concatenating axis.

Let’s see what happens when this condition is not met.

In [ ]:
# Arrays with incompatible shapes
array7 = np.array([7, 8, 9])

concat_error = np.concatenate([array4, array7], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Explanation:**
- Concatenation along `axis=1` fails because `array7` does not match the row count of `array4`.
- Always ensure compatible dimensions for <font color="skyblue">np.concatenate()</font>.



---

